/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Category controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, PagedListDtoOfCategoryResponse, CreateCategoryCommand, CategoryResponse, UpdateCategoryCommand } from "../models";

@Injectable({ providedIn: "root" })
export class CategoryService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getCategories(pageNumber?: number | string, pageSize?: number | string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PagedListDtoOfCategoryResponse>;
    getCategories(pageNumber?: number | string, pageSize?: number | string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PagedListDtoOfCategoryResponse>>;
    getCategories(pageNumber?: number | string, pageSize?: number | string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PagedListDtoOfCategoryResponse>>;
    getCategories(pageNumber?: number | string, pageSize?: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/category`;

        let params = new HttpParams();
        if (pageNumber != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageNumber, 'pageNumber');
        }
        if (pageSize != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageSize, 'pageSize');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    createCategory(createCategoryCommand: CreateCategoryCommand, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryResponse>;
    createCategory(createCategoryCommand: CreateCategoryCommand, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryResponse>>;
    createCategory(createCategoryCommand: CreateCategoryCommand, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryResponse>>;
    createCategory(createCategoryCommand: CreateCategoryCommand, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/category`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createCategoryCommand, requestOptions);
    }

    updateCategory(categoryId: number | string, updateCategoryCommand: UpdateCategoryCommand, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryResponse>;
    updateCategory(categoryId: number | string, updateCategoryCommand: UpdateCategoryCommand, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryResponse>>;
    updateCategory(categoryId: number | string, updateCategoryCommand: UpdateCategoryCommand, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryResponse>>;
    updateCategory(categoryId: number | string, updateCategoryCommand: UpdateCategoryCommand, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/category/${categoryId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, updateCategoryCommand, requestOptions);
    }

    deleteCategory(categoryId: number | string, observe?: 'body', options?: RequestOptions<'text'>): Observable<boolean>;
    deleteCategory(categoryId: number | string, observe?: 'response', options?: RequestOptions<'text'>): Observable<HttpResponse<boolean>>;
    deleteCategory(categoryId: number | string, observe?: 'events', options?: RequestOptions<'text'>): Observable<HttpEvent<boolean>>;
    deleteCategory(categoryId: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/category/${categoryId}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'text' as 'text',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
