/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Identity controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RegisterRequest, RequestOptions, LoginRequest, AccessTokenResponse, RefreshRequest, ResendConfirmationEmailRequest, ForgotPasswordRequest, ResetPasswordRequest, TwoFactorRequest, TwoFactorResponse, InfoResponse, InfoRequest } from "../models";

@Injectable({ providedIn: "root" })
export class IdentityService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiIdentityRegisterPost(registerRequest: RegisterRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiIdentityRegisterPost(registerRequest: RegisterRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiIdentityRegisterPost(registerRequest: RegisterRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiIdentityRegisterPost(registerRequest: RegisterRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/identity/register`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, registerRequest, requestOptions);
    }

    apiIdentityLoginPost(loginRequest: LoginRequest, useCookies?: boolean, useSessionCookies?: boolean, observe?: 'body', options?: RequestOptions<'json'>): Observable<AccessTokenResponse>;
    apiIdentityLoginPost(loginRequest: LoginRequest, useCookies?: boolean, useSessionCookies?: boolean, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AccessTokenResponse>>;
    apiIdentityLoginPost(loginRequest: LoginRequest, useCookies?: boolean, useSessionCookies?: boolean, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AccessTokenResponse>>;
    apiIdentityLoginPost(loginRequest: LoginRequest, useCookies?: boolean, useSessionCookies?: boolean, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/identity/login`;

        let params = new HttpParams();
        if (useCookies != null) {
            params = HttpParamsBuilder.addToHttpParams(params, useCookies, 'useCookies');
        }
        if (useSessionCookies != null) {
            params = HttpParamsBuilder.addToHttpParams(params, useSessionCookies, 'useSessionCookies');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, loginRequest, requestOptions);
    }

    apiIdentityRefreshPost(refreshRequest: RefreshRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<AccessTokenResponse>;
    apiIdentityRefreshPost(refreshRequest: RefreshRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AccessTokenResponse>>;
    apiIdentityRefreshPost(refreshRequest: RefreshRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AccessTokenResponse>>;
    apiIdentityRefreshPost(refreshRequest: RefreshRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/identity/refresh`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, refreshRequest, requestOptions);
    }

    confirmEmailIdentity(userId: string, code: string, changedEmail?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    confirmEmailIdentity(userId: string, code: string, changedEmail?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    confirmEmailIdentity(userId: string, code: string, changedEmail?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    confirmEmailIdentity(userId: string, code: string, changedEmail?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/identity/confirmEmail`;

        let params = new HttpParams();
        if (userId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, userId, 'userId');
        }
        if (code != null) {
            params = HttpParamsBuilder.addToHttpParams(params, code, 'code');
        }
        if (changedEmail != null) {
            params = HttpParamsBuilder.addToHttpParams(params, changedEmail, 'changedEmail');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiIdentityResendConfirmationEmailPost(resendConfirmationEmailRequest: ResendConfirmationEmailRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiIdentityResendConfirmationEmailPost(resendConfirmationEmailRequest: ResendConfirmationEmailRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiIdentityResendConfirmationEmailPost(resendConfirmationEmailRequest: ResendConfirmationEmailRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiIdentityResendConfirmationEmailPost(resendConfirmationEmailRequest: ResendConfirmationEmailRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/identity/resendConfirmationEmail`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, resendConfirmationEmailRequest, requestOptions);
    }

    apiIdentityForgotPasswordPost(forgotPasswordRequest: ForgotPasswordRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiIdentityForgotPasswordPost(forgotPasswordRequest: ForgotPasswordRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiIdentityForgotPasswordPost(forgotPasswordRequest: ForgotPasswordRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiIdentityForgotPasswordPost(forgotPasswordRequest: ForgotPasswordRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/identity/forgotPassword`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, forgotPasswordRequest, requestOptions);
    }

    apiIdentityResetPasswordPost(resetPasswordRequest: ResetPasswordRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiIdentityResetPasswordPost(resetPasswordRequest: ResetPasswordRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiIdentityResetPasswordPost(resetPasswordRequest: ResetPasswordRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiIdentityResetPasswordPost(resetPasswordRequest: ResetPasswordRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/identity/resetPassword`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, resetPasswordRequest, requestOptions);
    }

    apiIdentityManage2faPost(twoFactorRequest: TwoFactorRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<TwoFactorResponse>;
    apiIdentityManage2faPost(twoFactorRequest: TwoFactorRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TwoFactorResponse>>;
    apiIdentityManage2faPost(twoFactorRequest: TwoFactorRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TwoFactorResponse>>;
    apiIdentityManage2faPost(twoFactorRequest: TwoFactorRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/identity/manage/2fa`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, twoFactorRequest, requestOptions);
    }

    apiIdentityManageInfoGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<InfoResponse>;
    apiIdentityManageInfoGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<InfoResponse>>;
    apiIdentityManageInfoGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<InfoResponse>>;
    apiIdentityManageInfoGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/identity/manage/info`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiIdentityManageInfoPost(infoRequest: InfoRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<InfoResponse>;
    apiIdentityManageInfoPost(infoRequest: InfoRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<InfoResponse>>;
    apiIdentityManageInfoPost(infoRequest: InfoRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<InfoResponse>>;
    apiIdentityManageInfoPost(infoRequest: InfoRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/identity/manage/info`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, infoRequest, requestOptions);
    }
}
