/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { CategoryService } from "./category.service";
export { IdentityService } from "./identity.service";
export { PostService } from "./post.service";
export { TagService } from "./tag.service";
