/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Post controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, PagedListDtoOfPostResponse, CreatePostCommand, PostResponse, UpdatePostCommand, UpdatePostStatusCommand, CreateCommentCommand, UpdateCommentCommand, AddPostCategoryCommand, AddPostTagCommand } from "../models";

@Injectable({ providedIn: "root" })
export class PostService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllPublishedPost(pageNumber?: number | string, pageSize?: number | string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PagedListDtoOfPostResponse>;
    getAllPublishedPost(pageNumber?: number | string, pageSize?: number | string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PagedListDtoOfPostResponse>>;
    getAllPublishedPost(pageNumber?: number | string, pageSize?: number | string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PagedListDtoOfPostResponse>>;
    getAllPublishedPost(pageNumber?: number | string, pageSize?: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/post`;

        let params = new HttpParams();
        if (pageNumber != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageNumber, 'pageNumber');
        }
        if (pageSize != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageSize, 'pageSize');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    createPost(createPostCommand: CreatePostCommand, observe?: 'body', options?: RequestOptions<'json'>): Observable<number | string>;
    createPost(createPostCommand: CreatePostCommand, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<number | string>>;
    createPost(createPostCommand: CreatePostCommand, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<number | string>>;
    createPost(createPostCommand: CreatePostCommand, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/post`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createPostCommand, requestOptions);
    }

    getPostById(postId: number | string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PostResponse>;
    getPostById(postId: number | string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PostResponse>>;
    getPostById(postId: number | string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PostResponse>>;
    getPostById(postId: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/post/${postId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    updatePost(postId: number | string, updatePostCommand: UpdatePostCommand, observe?: 'body', options?: RequestOptions<'json'>): Observable<number | string>;
    updatePost(postId: number | string, updatePostCommand: UpdatePostCommand, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<number | string>>;
    updatePost(postId: number | string, updatePostCommand: UpdatePostCommand, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<number | string>>;
    updatePost(postId: number | string, updatePostCommand: UpdatePostCommand, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/post/${postId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, updatePostCommand, requestOptions);
    }

    deletePost(postId: number | string, observe?: 'body', options?: RequestOptions<'text'>): Observable<boolean>;
    deletePost(postId: number | string, observe?: 'response', options?: RequestOptions<'text'>): Observable<HttpResponse<boolean>>;
    deletePost(postId: number | string, observe?: 'events', options?: RequestOptions<'text'>): Observable<HttpEvent<boolean>>;
    deletePost(postId: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/post/${postId}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'text' as 'text',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    updatePostStatus(postId: number | string, updatePostStatusCommand: UpdatePostStatusCommand, observe?: 'body', options?: RequestOptions<'json'>): Observable<number | string>;
    updatePostStatus(postId: number | string, updatePostStatusCommand: UpdatePostStatusCommand, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<number | string>>;
    updatePostStatus(postId: number | string, updatePostStatusCommand: UpdatePostStatusCommand, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<number | string>>;
    updatePostStatus(postId: number | string, updatePostStatusCommand: UpdatePostStatusCommand, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/post/${postId}/status/change`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, updatePostStatusCommand, requestOptions);
    }

    addComment(postId: number | string, createCommentCommand: CreateCommentCommand, observe?: 'body', options?: RequestOptions<'json'>): Observable<number | string>;
    addComment(postId: number | string, createCommentCommand: CreateCommentCommand, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<number | string>>;
    addComment(postId: number | string, createCommentCommand: CreateCommentCommand, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<number | string>>;
    addComment(postId: number | string, createCommentCommand: CreateCommentCommand, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/post/${postId}/comment`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createCommentCommand, requestOptions);
    }

    updateComment(postId: number | string, commentId: number | string, updateCommentCommand: UpdateCommentCommand, observe?: 'body', options?: RequestOptions<'json'>): Observable<number | string>;
    updateComment(postId: number | string, commentId: number | string, updateCommentCommand: UpdateCommentCommand, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<number | string>>;
    updateComment(postId: number | string, commentId: number | string, updateCommentCommand: UpdateCommentCommand, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<number | string>>;
    updateComment(postId: number | string, commentId: number | string, updateCommentCommand: UpdateCommentCommand, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/post/${postId}/comment/${commentId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, updateCommentCommand, requestOptions);
    }

    deleteComment(postId: number | string, commentId: number | string, observe?: 'body', options?: RequestOptions<'json'>): Observable<number | string>;
    deleteComment(postId: number | string, commentId: number | string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<number | string>>;
    deleteComment(postId: number | string, commentId: number | string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<number | string>>;
    deleteComment(postId: number | string, commentId: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/post/${postId}/comment/${commentId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    addCategory(postId: number | string, addPostCategoryCommand: AddPostCategoryCommand, observe?: 'body', options?: RequestOptions<'json'>): Observable<number | string>;
    addCategory(postId: number | string, addPostCategoryCommand: AddPostCategoryCommand, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<number | string>>;
    addCategory(postId: number | string, addPostCategoryCommand: AddPostCategoryCommand, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<number | string>>;
    addCategory(postId: number | string, addPostCategoryCommand: AddPostCategoryCommand, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/post/${postId}/category/add`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, addPostCategoryCommand, requestOptions);
    }

    removeCategory(postId: number | string, categoryId: number | string, observe?: 'body', options?: RequestOptions<'json'>): Observable<number | string>;
    removeCategory(postId: number | string, categoryId: number | string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<number | string>>;
    removeCategory(postId: number | string, categoryId: number | string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<number | string>>;
    removeCategory(postId: number | string, categoryId: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/post/${postId}/category/remove/${categoryId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    addPostTag(postId: number | string, addPostTagCommand: AddPostTagCommand, observe?: 'body', options?: RequestOptions<'json'>): Observable<number | string>;
    addPostTag(postId: number | string, addPostTagCommand: AddPostTagCommand, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<number | string>>;
    addPostTag(postId: number | string, addPostTagCommand: AddPostTagCommand, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<number | string>>;
    addPostTag(postId: number | string, addPostTagCommand: AddPostTagCommand, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/post/${postId}/tag/add`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, addPostTagCommand, requestOptions);
    }

    removePostTag(postId: number | string, tagId: number | string, observe?: 'body', options?: RequestOptions<'json'>): Observable<number | string>;
    removePostTag(postId: number | string, tagId: number | string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<number | string>>;
    removePostTag(postId: number | string, tagId: number | string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<number | string>>;
    removePostTag(postId: number | string, tagId: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/post/${postId}/tag/remove/${tagId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
