/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Tag controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, PagedListDtoOfTagResponse, CreateTagCommand, TagResponse, UpdateTagCommand } from "../models";

@Injectable({ providedIn: "root" })
export class TagService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllTags(pageNumber?: number | string, pageSize?: number | string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PagedListDtoOfTagResponse>;
    getAllTags(pageNumber?: number | string, pageSize?: number | string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PagedListDtoOfTagResponse>>;
    getAllTags(pageNumber?: number | string, pageSize?: number | string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PagedListDtoOfTagResponse>>;
    getAllTags(pageNumber?: number | string, pageSize?: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tag`;

        let params = new HttpParams();
        if (pageNumber != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageNumber, 'pageNumber');
        }
        if (pageSize != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageSize, 'pageSize');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    createTag(createTagCommand: CreateTagCommand, observe?: 'body', options?: RequestOptions<'json'>): Observable<TagResponse>;
    createTag(createTagCommand: CreateTagCommand, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TagResponse>>;
    createTag(createTagCommand: CreateTagCommand, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TagResponse>>;
    createTag(createTagCommand: CreateTagCommand, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tag`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createTagCommand, requestOptions);
    }

    getTagDetailsById(tagId: number | string, observe?: 'body', options?: RequestOptions<'json'>): Observable<TagResponse>;
    getTagDetailsById(tagId: number | string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TagResponse>>;
    getTagDetailsById(tagId: number | string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TagResponse>>;
    getTagDetailsById(tagId: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tag/${tagId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    updateTag(tagId: number | string, updateTagCommand: UpdateTagCommand, observe?: 'body', options?: RequestOptions<'json'>): Observable<TagResponse>;
    updateTag(tagId: number | string, updateTagCommand: UpdateTagCommand, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TagResponse>>;
    updateTag(tagId: number | string, updateTagCommand: UpdateTagCommand, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TagResponse>>;
    updateTag(tagId: number | string, updateTagCommand: UpdateTagCommand, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tag/${tagId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, updateTagCommand, requestOptions);
    }

    deleteTag(tagId: number | string, observe?: 'body', options?: RequestOptions<'text'>): Observable<boolean>;
    deleteTag(tagId: number | string, observe?: 'response', options?: RequestOptions<'text'>): Observable<HttpResponse<boolean>>;
    deleteTag(tagId: number | string, observe?: 'events', options?: RequestOptions<'text'>): Observable<HttpEvent<boolean>>;
    deleteTag(tagId: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tag/${tagId}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'text' as 'text',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
