/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface AccessTokenResponse {
    tokenType?: null | string;
    accessToken: string;
    expiresIn: number | string;
    refreshToken: string;
}

export interface AddPostCategoryCommand {
    postId: number | string;
    categoryId: number | string;
}

export interface AddPostTagCommand {
    postId: number | string;
    tag: string;
}

export interface CategoryResponse {
    categoryId: number | string;
    name: string;
    description: string;
}

export interface CommentResponse {
    commentId: number | string;
    commentText: string;
}

export interface CreateCategoryCommand {
    name: string;
    description: string;
}

export interface CreateCommentCommand {
    postId: number | string;
    text: string;
}

export interface CreatePostCommand {
    title: string;
    text: string;
    slug: string;
    status?: PostStatus;
}

export interface CreateTagCommand {
    name: string;
    description: string;
}

export interface ForgotPasswordRequest {
    email: string;
}

export interface HttpValidationProblemDetails {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
    errors?: Record<string, Array<string>>;
}

export interface InfoRequest {
    newEmail?: null | string;
    newPassword?: null | string;
    oldPassword?: null | string;
}

export interface InfoResponse {
    email: string;
    isEmailConfirmed: boolean;
}

export interface LoginRequest {
    email: string;
    password: string;
    twoFactorCode?: null | string;
    twoFactorRecoveryCode?: null | string;
}

export interface PagedListDtoOfCategoryResponse {
    totalCount?: number | string;
    items?: null | any[];
}

export interface PagedListDtoOfPostResponse {
    totalCount?: number | string;
    items?: null | any[];
}

export interface PagedListDtoOfTagResponse {
    totalCount?: number | string;
    items?: null | any[];
}

export interface PostCategoryResponse {
    categoryId: number | string;
    categoryName: string;
}

export interface PostResponse {
    postId: number | string;
    title: string;
    slug: string;
    status: PostStatus;
    statusText: string;
    text: string;
    comments: Array<CommentResponse>;
    categories: Array<PostCategoryResponse>;
    tags: Array<PostTagResponse>;
}

export type PostStatus = number;

export interface PostTagResponse {
    tagId: number | string;
    tagName: string;
}

export interface RefreshRequest {
    refreshToken: string;
}

export interface RegisterRequest {
    email: string;
    password: string;
}

export interface ResendConfirmationEmailRequest {
    email: string;
}

export interface ResetPasswordRequest {
    email: string;
    resetCode: string;
    newPassword: string;
}

export interface TagResponse {
    tagId: number | string;
    name: string;
    description: string;
}

export interface TwoFactorRequest {
    enable?: null | boolean;
    twoFactorCode?: null | string;
    resetSharedKey?: boolean;
    resetRecoveryCodes?: boolean;
    forgetMachine?: boolean;
}

export interface TwoFactorResponse {
    sharedKey: string;
    recoveryCodesLeft: number | string;
    recoveryCodes?: null | any[];
    isTwoFactorEnabled: boolean;
    isMachineRemembered: boolean;
}

export interface UpdateCategoryCommand {
    categoryId: number | string;
    name: string;
    description: string;
}

export interface UpdateCommentCommand {
    postId: number | string;
    commentId: number | string;
    commentText: string;
}

export interface UpdatePostCommand {
    postId: number | string;
    title: string;
    slug: string;
    text: string;
}

export interface UpdatePostStatusCommand {
    postId: number | string;
    status: PostStatus;
}

export interface UpdateTagCommand {
    tagId: number | string;
    name: string;
    description: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
